name: Deployment Project
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run linter
        run: |
          npm run lint

      - name: Run tests
        run: |
          npm run test
          
  deploy: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code/Get code
        uses: actions/checkout@v4

      - name: Install nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build project
        run: |
          npm run build

      - name: Deploy to server
        run: |
          echo "Deploying to server..."
          # Add your deployment commands here