name: Events Demo
on: 
    pull_request:
      types: [opened, edited, reopened, synchronize]
    workflow_dispatch:
    push:
      branches:
        - main # Matches the main branch
        - 'dev-*'  # Matches branches like dev-1, dev-2-this-is-new, etc.
        - 'feat/**' # Matches branches like feat/new feat/new/button
      paths-ignore:
        - 'README.md' # Ignore changes to README.md
        - 'docs/**' # Ignore changes to docs folder
        - '.github/workflows/**' # Ignore changes to workflows folder
jobs:
  handle-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
          echo "Event name: ${{ toJson(github.event) }}"
          echo "Action: ${{ github.event.action }}"
          echo "Repository: ${{ github.repository }}"
          echo "Sender: ${{ github.actor }}"
          echo "Event details:"
          echo "${{ toJson(github.event) }}"