name: Handle Issues
on: issues
jobs:
  handle-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
            echo "Event name: ${{ toJson(github.event) }}"
            echo "Action: ${{ github.event.action }}"
            echo "Issue title: ${{ github.event.issue.title }}"
            echo "Issue body: ${{ github.event.issue.body }}"
            echo "Issue number: ${{ github.event.issue.number }}"
            echo "Repository: ${{ github.repository }}"
            echo "Sender: ${{ github.actor }}"
            echo "Event details:"
            echo "${{ toJson(github.event) }}"