name: Output information
on: [workflow_dispatch]
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Output information
        run: |
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v
          echo "Current directory:"
          pwd

      - name: Output GitHub context
        run: |
          echo "Repository:"
          echo "${{ toJson(github.repository) }}"
        #   echo "Workflow name:"
        #   echo "${{ toJson(github.workflow) }}"
        #   echo "Run ID:"
        #   echo "${{ toJson(github.run_id) }}"
        # echo "GitHub context:"
        # echo "${{ toJson(github) }}"
        # echo "GitHub event:"
        # echo "${{ toJson(github.event) }}"
        # echo "GitHub workflow:"
        # echo "${{ toJson(github.workflow) }}"
        # echo "GitHub action:"
        # echo "${{ toJson(github.action) }}"
        # echo "GitHub job:"
        # echo "${{ toJson(github.job) }}"